import type { Department, Program, Tenant } from "./types";

export const TENANT: Tenant = {
  id: "tenant-aldridge",
  name: "Aldridge University",
  shortName: "Aldridge",
  crest: "A",
  plan: "Enterprise · Spring 2026",
  activeSemesterId: "sem-spring-2026",
};

export const DEPARTMENTS: Department[] = [
  { id: "dept-cs", code: "CS", name: "Computer Science" },
  { id: "dept-math", code: "MATH", name: "Mathematics" },
  { id: "dept-phys", code: "PHYS", name: "Physics" },
  { id: "dept-bio", code: "BIO", name: "Biology" },
  { id: "dept-chem", code: "CHEM", name: "Chemistry" },
  { id: "dept-eng", code: "ENG", name: "English" },
  { id: "dept-lit", code: "LIT", name: "Comparative Literature" },
  { id: "dept-hist", code: "HIST", name: "History" },
  { id: "dept-phil", code: "PHIL", name: "Philosophy" },
  { id: "dept-econ", code: "ECON", name: "Economics" },
  { id: "dept-soc", code: "SOC", name: "Sociology" },
  { id: "dept-poli", code: "POLI", name: "Political Science" },
  { id: "dept-art", code: "ART", name: "Art History" },
  { id: "dept-mus", code: "MUS", name: "Music" },
  { id: "dept-ling", code: "LING", name: "Linguistics" },
];

export const PROGRAMS: Program[] = [
  { id: "prog-cs-bs", code: "CS-BS", name: "B.S. Computer Science", degreeType: "BS", departmentId: "dept-cs" },
  { id: "prog-cs-ms", code: "CS-MS", name: "M.S. Computer Science", degreeType: "MS", departmentId: "dept-cs" },
  { id: "prog-cs-phd", code: "CS-PHD", name: "Ph.D. Computer Science", degreeType: "PhD", departmentId: "dept-cs" },
  { id: "prog-math-bs", code: "MATH-BS", name: "B.S. Mathematics", degreeType: "BS", departmentId: "dept-math" },
  { id: "prog-math-phd", code: "MATH-PHD", name: "Ph.D. Mathematics", degreeType: "PhD", departmentId: "dept-math" },
  { id: "prog-phys-bs", code: "PHYS-BS", name: "B.S. Physics", degreeType: "BS", departmentId: "dept-phys" },
  { id: "prog-bio-bs", code: "BIO-BS", name: "B.S. Molecular Biology", degreeType: "BS", departmentId: "dept-bio" },
  { id: "prog-bio-phd", code: "BIO-PHD", name: "Ph.D. Biology", degreeType: "PhD", departmentId: "dept-bio" },
  { id: "prog-chem-bs", code: "CHEM-BS", name: "B.S. Chemistry", degreeType: "BS", departmentId: "dept-chem" },
  { id: "prog-eng-ba", code: "ENG-BA", name: "B.A. English", degreeType: "BA", departmentId: "dept-eng" },
  { id: "prog-lit-ba", code: "LIT-BA", name: "B.A. Comparative Literature", degreeType: "BA", departmentId: "dept-lit" },
  { id: "prog-lit-ma", code: "LIT-MA", name: "M.A. Comparative Literature", degreeType: "MA", departmentId: "dept-lit" },
  { id: "prog-hist-ba", code: "HIST-BA", name: "B.A. History", degreeType: "BA", departmentId: "dept-hist" },
  { id: "prog-phil-ba", code: "PHIL-BA", name: "B.A. Philosophy", degreeType: "BA", departmentId: "dept-phil" },
  { id: "prog-econ-bs", code: "ECON-BS", name: "B.S. Economics", degreeType: "BS", departmentId: "dept-econ" },
  { id: "prog-econ-phd", code: "ECON-PHD", name: "Ph.D. Economics", degreeType: "PhD", departmentId: "dept-econ" },
  { id: "prog-soc-ba", code: "SOC-BA", name: "B.A. Sociology", degreeType: "BA", departmentId: "dept-soc" },
  { id: "prog-poli-ba", code: "POLI-BA", name: "B.A. Political Science", degreeType: "BA", departmentId: "dept-poli" },
  { id: "prog-art-ba", code: "ART-BA", name: "B.A. Art History", degreeType: "BA", departmentId: "dept-art" },
  { id: "prog-mus-bm", code: "MUS-BM", name: "B.M. Music Performance", degreeType: "BA", departmentId: "dept-mus" },
  { id: "prog-ling-ba", code: "LING-BA", name: "B.A. Linguistics", degreeType: "BA", departmentId: "dept-ling" },
];

export const BUILDINGS = [
  "Aldridge Hall",
  "Bowen Center",
  "Carlton Sciences",
  "Ducey Library",
  "Eastwood Pavilion",
  "Foley Humanities",
  "Greene Engineering",
  "Halverson Theatre",
  "Ingram Hall",
  "Jefferson Commons",
  "Kessler Quad",
  "Linden Studios",
];

// Lecture-room number prefixes (e.g., "112", "204") will be generated.

export const COURSE_TITLE_PREFIXES_BY_DEPT: Record<string, string[]> = {
  CS: [
    "Introduction to",
    "Distributed",
    "Programming Languages and",
    "Algorithms in",
    "Foundations of",
    "Advanced",
    "Topics in",
    "Operating",
    "Computational",
    "Statistical",
  ],
  MATH: [
    "Calculus of",
    "Linear",
    "Real",
    "Abstract",
    "Numerical",
    "Discrete",
    "Topics in",
    "Foundations of",
    "Topology of",
    "Combinatorial",
  ],
  PHYS: [
    "Classical",
    "Quantum",
    "Statistical",
    "Mathematical",
    "Experimental",
    "Modern",
    "Topics in",
    "Foundations of",
    "Computational",
    "Relativistic",
  ],
  BIO: [
    "Molecular",
    "Cellular",
    "Organismal",
    "Evolutionary",
    "Ecological",
    "Comparative",
    "Quantitative",
    "Topics in",
    "Foundations of",
    "Developmental",
  ],
  CHEM: [
    "Organic",
    "Inorganic",
    "Physical",
    "Analytical",
    "Theoretical",
    "Computational",
    "Topics in",
    "Spectroscopy and",
    "Foundations of",
    "Quantum",
  ],
  ENG: [
    "American",
    "British",
    "Modern",
    "Renaissance",
    "Topics in",
    "Foundations of",
    "Writing the",
    "Studies in",
    "Postwar",
    "Romantic",
  ],
  LIT: [
    "Postcolonial",
    "Comparative",
    "Translation and",
    "Modernist",
    "Topics in",
    "Foundations of",
    "Studies in",
    "Continental",
    "Pre-modern",
    "Diasporic",
  ],
  HIST: [
    "Modern",
    "Ancient",
    "Topics in",
    "Foundations of",
    "Comparative",
    "Atlantic",
    "Mediterranean",
    "Imperial",
    "Twentieth-Century",
    "Early Modern",
  ],
  PHIL: [
    "Modern",
    "Ancient",
    "Topics in",
    "Foundations of",
    "Comparative",
    "Continental",
    "Analytic",
    "Practical",
    "Political",
    "Studies in",
  ],
  ECON: [
    "Microeconomic",
    "Macroeconomic",
    "Behavioral",
    "Development",
    "Topics in",
    "Foundations of",
    "Comparative",
    "Labor",
    "Public",
    "Quantitative",
  ],
  SOC: [
    "Urban",
    "Comparative",
    "Topics in",
    "Foundations of",
    "Quantitative",
    "Cultural",
    "Political",
    "Studies in",
    "Historical",
    "Theory of",
  ],
  POLI: [
    "Comparative",
    "Topics in",
    "Foundations of",
    "American",
    "Quantitative",
    "Studies in",
    "International",
    "Public",
    "Theory of",
    "Political",
  ],
  ART: [
    "Modern",
    "Renaissance",
    "Topics in",
    "Foundations of",
    "Comparative",
    "Studies in",
    "Theory of",
    "Imperial",
    "Pre-modern",
    "Contemporary",
  ],
  MUS: [
    "Topics in",
    "Foundations of",
    "Studies in",
    "Theory of",
    "Comparative",
    "Performance and",
    "Early",
    "Modern",
    "Composition and",
    "History of",
  ],
  LING: [
    "Topics in",
    "Foundations of",
    "Studies in",
    "Theory of",
    "Comparative",
    "Historical",
    "Sociolinguistic",
    "Computational",
    "Phonological",
    "Syntactic",
  ],
};

export const COURSE_TITLE_SUBJECTS_BY_DEPT: Record<string, string[]> = {
  CS: [
    "Systems",
    "Algorithms",
    "Theory",
    "Networks",
    "Databases",
    "Compilers",
    "Graphics",
    "Machine Learning",
    "Cryptography",
    "Programming",
    "Concurrency",
    "Software Engineering",
    "Human–Computer Interaction",
    "Interface Systems",
  ],
  MATH: [
    "Analysis",
    "Algebra",
    "Geometry",
    "Topology",
    "Number Theory",
    "Probability",
    "Statistics",
    "Combinatorics",
    "Equations",
    "Variables",
  ],
  PHYS: [
    "Mechanics",
    "Electrodynamics",
    "Optics",
    "Thermodynamics",
    "Field Theory",
    "Cosmology",
    "Particles",
    "Solid State",
    "Astrophysics",
    "Methods",
  ],
  BIO: [
    "Genetics",
    "Evolution",
    "Neuroscience",
    "Microbiology",
    "Ecology",
    "Physiology",
    "Anatomy",
    "Biochemistry",
    "Immunology",
    "Botany",
  ],
  CHEM: [
    "Chemistry",
    "Synthesis",
    "Kinetics",
    "Thermochemistry",
    "Electrochemistry",
    "Biochemistry",
    "Polymers",
    "Catalysis",
    "Materials",
    "Methods",
  ],
  ENG: [
    "Literature",
    "Poetry",
    "Novel",
    "Drama",
    "Criticism",
    "Rhetoric",
    "Fiction",
    "Essay",
    "Prose",
    "Composition",
  ],
  LIT: [
    "Literature",
    "Poetics",
    "Translation",
    "Memory",
    "Form",
    "Genre",
    "Voice",
    "World Literature",
    "Aesthetics",
    "Narrative",
  ],
  HIST: [
    "Europe",
    "Asia",
    "Africa",
    "the Americas",
    "Trade",
    "Empires",
    "Revolutions",
    "the Cold War",
    "the Mediterranean",
    "the Pacific",
  ],
  PHIL: [
    "Ethics",
    "Logic",
    "Mind",
    "Knowledge",
    "Language",
    "Aesthetics",
    "Metaphysics",
    "Phenomenology",
    "Free Will",
    "Justice",
  ],
  ECON: [
    "Economics",
    "Markets",
    "Trade",
    "Labor",
    "Inequality",
    "Game Theory",
    "Forecasting",
    "Growth",
    "Finance",
    "Behavior",
  ],
  SOC: [
    "Sociology",
    "Inequality",
    "Migration",
    "Networks",
    "Religion",
    "Family",
    "Race",
    "Class",
    "Movements",
    "Cities",
  ],
  POLI: [
    "Politics",
    "Democracy",
    "Institutions",
    "Conflict",
    "Diplomacy",
    "Public Policy",
    "Voting",
    "Parties",
    "Constitutions",
    "Theory",
  ],
  ART: [
    "Art",
    "Painting",
    "Sculpture",
    "Architecture",
    "Photography",
    "Curatorial Practice",
    "Modernism",
    "Iconography",
    "Visual Culture",
    "Patronage",
  ],
  MUS: [
    "Music",
    "Composition",
    "Performance",
    "Orchestra",
    "Counterpoint",
    "Harmony",
    "Ethnomusicology",
    "Notation",
    "Improvisation",
    "Listening",
  ],
  LING: [
    "Syntax",
    "Semantics",
    "Phonology",
    "Morphology",
    "Pragmatics",
    "Language Change",
    "Bilingualism",
    "Acquisition",
    "Discourse",
    "Field Methods",
  ],
};
